version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    restart: always
  web:
    build: ./
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
    
# version: '3.5'
# services:
#   server:
#     build: 
#       context: ./
#     restart: always
#     ports:
#       - 3000:3000
#     networks:
#       - db-net
#     depends_on:
#       - db
#   db:
#     platform: linux/amd64
#     image: mysql:5.7
#     command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#     restart: always
#     volumes:
#       - ./mysql/init:/docker-entrypoint-initdb.d
#       - ./mysql/data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#     networks:
#       - db-net
#     ports:
#       - 8086:3306
  
# networks:
#   db-net: